### ISSUE TITLE
JSIConverter support for optional value

### ISSUE THREAD

**Issue by wcandillon** [margelo/react-native-filament#211]
In its current form, the JSIConverter<std::optional> doesn't support the absence of the parameter.
For instance:
```
// defined in C++ as requestAdapter(std::optional<std::shared_ptr<GPURequestAdapterOptions>> options)
// ✅ Works
requestAdapter(undefined)
requestAdapter({})
// ❌ Doesn't work
requestAdapter()
```

The following converter seems to work well (I couldn't make a PR without forking):
```
// std::optional<T> <> T | undefined
template <typename TInner> struct JSIConverter<std::optional<TInner>> {
  static std::optional<TInner> fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
   // Here the arg.isNull() could be litigious, we will probably remove it on our side.
    if (&arg == nullptr || arg.isUndefined() || arg.isNull()) {
      return std::nullopt;
    } else {
      return JSIConverter<TInner>::fromJSI(runtime, std::move(arg));
    }
  }
  static jsi::Value toJSI(jsi::Runtime& runtime, const std::optional<TInner>& arg) {
    if (arg == std::nullopt) {
      return jsi::Value::undefined();
    } else {
      return JSIConverter<TInner>::toJSI(runtime, arg.value());
    }
  }
};
```

**Comment by hannojg** [comment]
Closing this issue here as its probably better discussed in "the new repo" 😊

**Comment by mrousavy** [comment]
Yup - react-native-nitro already supports optional parameters since https://github.com/mrousavy/react-native-nitro/pull/9.


All **trailing** optional values are computed at compiletime, and no overhead is introduced.

Assuming we have this function:

```ts
interface TestObject extends HybridObject {
  tryOptionalParams(num: number, bo: boolean, str?: string): void
}
```

You can call it like so:

```ts
obj.tryOptionalParams(55, true, "hello!") ✅
obj.tryOptionalParams(55, true) ✅
```

but once you pass one arg too much or too little, it will throw:

```ts
obj.tryOptionalParams(55, true, "hello!", "another extra arg!!!") ❌
```

```diff
-  Error: TestObject.tryOptionalParams(...) expected between 2 and 3 arguments, but received 4!
```

**Comment by wcandillon** [comment]
We've been using Hybrid Objects from Filament and added support of optional parameters but our plan is of course to switch to nitro, excited for it :)Btw we may be able to also contribute back to Filament too.Part of RNWGPU, we offer the following API:
```
// in WGPU people can synchronously write for instance
ref.current.getContext("webgpu").canvas.width
// But we also offer a more generic API to boot up Skia or potentially filament
ref.current.getNativeSurface(); // return pointer to a native window or metal layer.
<Canvas ref={ref} />
```

The goal is to have a generic canvas element like on the web.
 In Skia we don't care to have a dependency to WGPU because we will use WGPU as a dependency eventually but we understand that for this to be useful to Filament it probably needs to be a separate package. (Filament doesn't support Dawn and or WGPU right?)

**Comment by mrousavy** [comment]
Nitro 0.1.7 is released and working pretty stable in our tests.
- [react-native-nitro/example](https://github.com/mrousavy/react-native-nitro/tree/main/example) covers 83 common test cases for hybrid objects, all of them are passing ✅
- @boorad is already migrating [react-native-quick-crypto](https://github.com/margelo/react-native-quick-crypto) to Nitro Modules, and the **Random** module is already a Hybrid Object - afaik everything is working here, including ArrayBuffers, `future`/async, and primitive types or objects.
- @hannojg started a bit on migrating [react-native-filament](https://github.com/margelo/react-native-filament) to Nitro, but will continue to do so later this week.

I'd appreciate any feedback on Nitro if/once you also start integrating it in WebGPU :) As always I'm available for questions.

**Comment by wcandillon** [comment]
Migration might be the first thing we do after the release 🙏
