### ISSUE TITLE
android build error: package dalvik.annotation.optimization does not exist

### ISSUE THREAD

**Issue by Gautham495** [margelo/react-native-filament#237]
I have successfully ran the library in iOS, but in android when I try to build it is not working.

Attaching the logs below.

/Users/gauthamvijayan/gauthamvijaydemoapp/node_modules/react-native-filament/android/src/main/java/com/margelo/filament/FilamentChoreographer.java:11: error: package dalvik.annotation.optimization does not exist
import dalvik.annotation.optimization.FastNative;
                                     ^
/Users/gauthamvijayan/gauthamvijaydemoapp/node_modules/react-native-filament/android/src/main/java/com/margelo/filament/FilamentChoreographer.java:65: error: cannot find symbol
    @FastNative
     ^
  symbol:   class FastNative
  location: class FilamentChoreographer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/gauthamvijayan/gauthamvijaydemoapp/node_modules/react-native-filament/android/src/oldarch/com/margelo/filament/FilamentViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-filament:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Please let me know what I should do.

**Comment by hannojg** [comment]
What is the output of the following commands for you:

```
java -version
which java
```

?

**Comment by Gautham495** [comment]
I am using 71.0 due to some work constraints. What is the minimum version of RN I need to have for this package to run in android?

**Comment by Gautham495** [comment]
@hannojg

**Comment by hannojg** [comment]
I think the minimum is 0.73

**Comment by Gautham495** [comment]
Solved when using react native version 0.73.8. Here is the working video on the latest android 15 published in youtube.

DeadPool 3D model - React Native with react-native-filament library #deadpool #reactnative #android
https://youtube.com/shorts/uHW7GqtYJVg?feature=share

Closing this issue now. 

Seriously awesome stuff.
