### ISSUE TITLE
changing any model prop value throws uncaught Error helper.isWorkletSahredValue is not a function

### ISSUE THREAD

**Issue by bidah** [margelo/react-native-filament#242]
reproducible example: <https://github.com/bidah/react-native-filament-testing-app>

*This setup is using Expo.

The screen is rendering as expected but upon changing any model prop value like `rotate` the error  shows but if dismissed the change has been applied to the model.

```
Filament Error: 0,_helper.isWorkletSharedValue is not a function (it is undefined), js engine: Filament
```

![CleanShot 2024-07-22 at 12 06 50](https://github.com/user-attachments/assets/218094ac-69ca-445d-bd68-450ba31ccf9f)

**Comment by hannojg** [comment]
Thanks for the reproduction, checking now!

**Comment by hannojg** [comment]
This should be fixed in https://github.com/margelo/react-native-filament/releases/tag/v1.5.1

The version will be online in ~5min - can you confirm its fixed>

**Comment by hannojg** [comment]
Tested the new version in your reproduction app - looks like its fixed!

**Comment by bidah** [comment]
working! thanks @hannojg
