### ISSUE TITLE
Update Material: Change Tint color, replace map

### ISSUE THREAD

**Issue by hannojg** [margelo/react-native-filament#55]
Conversation here: https://margelo.slack.com/archives/C06GRRANY3V/p1710253225432469?thread_ts=1710239689.758209&cid=C06GRRANY3V

**Comment by sarthakpranesh** [comment]
Hi @hannojg and @saschagehlich 
Is their any documentation on how we can achieve this? or a small example for the same?

I have a custom native component implementation for 3D model viewing using filament and the only blocker for moving to this package right now seems to be material color change as I couldn't find anything in the existing documentation for this.

**Comment by hannojg** [comment]
Yeah, it's possible. You need to change parameters on the material. If the material is using a colours the parameter is usually set with the `baseColorFactor` parameter. Yo can follow the docs here to understand how to pick a certain entity with a material (if you use the native filament already this should feel natural to you using the imperative api):

- https://margelo.github.io/react-native-filament/docs/guides/images#applying-textures

Then you can do:

```ts
const entity = asset.getFirstEntityByName("Wings")
const materialInstance = renderableManager.getMaterialInstanceAt(entity, 1)
materialInstance.setFloat4Parameter('baseColorFactor', [s, r, g, b])
```

- https://margelo.github.io/react-native-filament/docs/api/interfaces/MaterialInstance#setfloat4parameter

**Comment by sarthakpranesh** [comment]
Thanks for helping out @hannojg. I'll give this a try, looking forward to the `EntitySelector` approach.
